version: "1.0"

services:
  db:
    container_name: impok_db
    image: postgres:latest
    environment:
      POSTGRES_USER: impok_user
      POSTGRES_PASSWORD: impok_pass
      POSTGRES_DB: impok_db
    volumes:
      - ./postgres_data:/var/lib/data/
    ports:
      - "5431:5432"

#  pgadmin:
#    container_name: pgadmin_chart
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: chart@mail.ru
#      PGADMIN_DEFAULT_PASSWORD: chart
#    ports:
#      - "5050:80"